name: Run Real Time + Run Ruptura Canal

on:
  schedule:
    - cron: "****** * * * *" # Cada 6 minutos
  workflow_dispatch:     

jobs:
  realtime_data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge
        
      - name: Instalar dependencias y ejecutar notebook RealTime
        shell: bash -l {0}
        run: |
          conda install -y pip papermill ipykernel pandas numpy scikit-learn yfinance
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill notebooks/downLoadDataRealtimeAlpha_final_V1.ipynb /dev/null -k python3

      - name: Subir cambios
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git config user.email "casaslinder@gmail.com"
          git config user.name "LinderCasas"
          git add .
          git commit -m "Update data Real Time"
          git push https://x-access-token:${TOKEN}@github.com/LinderCa/Notebooks_Trading.git

      
  ruptura_canal: 
    needs: realtime_data # Paso que depende del anterior
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Instalar dependencias y ejecutar notebook Ruptura canal
        shell: bash -l {0}
        run: |
          conda install -y pip papermill ipykernel pandas numpy scikit-learn yfinance
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill notebooks/BreakOut_Indicator_v9.ipynb /dev/null -k python3

      - name: subir cambios al repo
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git config user.email "casaslinder@gmail.com"
          git config user.name "LinderCasas"
          git add .
          git commit -m "Update resultados del notebook" || echo "Nada para comitear"
          git pull --rebase
          git push https://x-access-token:${TOKEN}@github.com/LinderCa/Notebooks_Trading.git
                
