name: Ejecutar Notebook

on:
  schedule:
    - cron: "0 12 * * *"  # Cada día a las 12:00 UTC
  workflow_dispatch:      # Para ejecutarlo manualmente

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Cachear paquetes de pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install papermill ipykernel

      - name: Registrar kernel para papermill
        run: |
          python -m ipykernel install --user --name python3

      - name: Ejecutar notebook
        run: |
          papermill notebooks/BreakOut_Indicator_v8.ipynb /dev/null -k python3
