name: Run Notebook at Midnight

on:
  schedule:
    # Se ejecuta todos los días a medianoche (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite ejecución manual si es necesario

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          pip install jupyter ipykernel papermill

      - name: Register Python kernel
        run: python -m ipykernel install --user --name python3

      - name: Run notebook
        run: |
          papermill notebooks/BreakOut_Indicator_v8.ipynb notebooks/breakout_output.ipynb -k python3

      