name: Run Specific Notebooks Every 5 Minutes

on:
  schedule:
    # Programación para ejecutar cada 5 minutos
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecución manual si es necesario

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter ipykernel papermill

      - name: Register Python kernel
        run: python -m ipykernel install --user --name=python3

      - name: Run notebooks
        run: |
          papermill notebooks/BreakOut_Indicator_v8.ipynb notebooks/BreakOut_Indicator_v8_output.ipynb -k python3

      # 5. Guarda el archivo de salida como artifact
      - name: Upload output notebook
        uses: actions/upload-artifact@v3
        with:
          name: BreakOut_Indicator_output_notebook
          path: notebooks/BreakOut_Indicator_v8_output.ipynb