name: Run breakout notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # Esto es Ubuntu 24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        pip install jupyter ipykernel papermill

    - name: Run notebook
      run: |
        papermill notebooks/BreakOut_Indicator_v8.ipynb notebooks/breakout_output.ipynb -k python3

      
