name: Run breakout notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # Esto es Ubuntu 24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install TA-Lib from source
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget python3-dev

        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xvzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install

    - name: Install Python dependencies
      run: |
        export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
        export CFLAGS="-I/usr/include"
        export LDFLAGS="-L/usr/lib"

        python -m pip install --upgrade pip
        conda install TA-Lib
        conda install -r requirements.txt
        conda install jupyter ipykernel papermill

    - name: Run notebook
      run: |
        papermill notebooks/BreakOut_Indicator_v8.ipynb notebooks/breakout_output.ipynb -k python3

      
